// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn7b4zkm9QEragHyYRLdStqA8l1eTYhA',
    appId: '1:135426504411:web:5b740368ed5ea18430befe',
    messagingSenderId: '135426504411',
    projectId: 'neura-note',
    authDomain: 'neura-note.firebaseapp.com',
    storageBucket: 'neura-note.firebasestorage.app',
    measurementId: 'G-MXRXNZVWGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8hmPFQgtL3pmI8HnWQjX0XenJRM69eY',
    appId: '1:648242658408:android:16b31cbda422f7090ccfdd',
    messagingSenderId: '648242658408',
    projectId: 'neura-note-ffd66',
    databaseURL: 'https://neura-note-ffd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'neura-note-ffd66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-bELrhV6qX27404f7VMtYxBr_-KtVg0',
    appId: '1:648242658408:ios:6d820c0b7aef63380ccfdd',
    messagingSenderId: '648242658408',
    projectId: 'neura-note-ffd66',
    databaseURL: 'https://neura-note-ffd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'neura-note-ffd66.firebasestorage.app',
    iosBundleId: 'com.example.neuranotteai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSdCYR9s6NbTZhub6Qt5OVKFFB5AojrHg',
    appId: '1:135426504411:ios:2edc6f61c14892a730befe',
    messagingSenderId: '135426504411',
    projectId: 'neura-note',
    storageBucket: 'neura-note.firebasestorage.app',
    iosClientId: '135426504411-vh7nkmjb0ilhph62v8t4j4i5tdhk2tsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuranoteai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcn7b4zkm9QEragHyYRLdStqA8l1eTYhA',
    appId: '1:135426504411:web:98d4e34886cee7ff30befe',
    messagingSenderId: '135426504411',
    projectId: 'neura-note',
    authDomain: 'neura-note.firebaseapp.com',
    storageBucket: 'neura-note.firebasestorage.app',
    measurementId: 'G-9YMZ53PXZM',
  );
}